### Import Library

In [1]:
import pandas as pd
import re

### Load Dataset

In [2]:
df = pd.read_csv('../data/dataMentah.csv')
df.head()

,Judul,Waktu,Link,Content,tag1,tag2,tag3,tag4,tag5,source
0,"Viral Isu PHK Buruh Gudang Garam, Said Iqbal: ...",6 September 2025,https://nasional.kompas.com/read/2025/09/06/14...,"JAKARTA, KOMPAS.com – Presiden Konfederasi Se...",Said Iqbal,industri rokok,PT Gudang Garam,PHK massal,phk massal 2025 terbaru,kompas
1,"Gempa M 5,3 Guncang Pulau Doi Maluku Utara","Senin, 12 Agu 2024 21:58 WIB",https://news.detik.com/berita/d-7486691/gempa-...,"Gempa bumi berkekuatan magnitudo (M) 5,3 mengg...",pulau doi,gempa,NaN,NaN,NaN,detik
2,"Toko Emas Palsu di Riau Dibongkar Polisi, Perh...","Rabu, 30 Jul 2025 22:22 WIB",https://news.detik.com/melindungi-tuah-marwah/...,Satreskrim Polres Bengkalis membongkar praktik...,pemalsuan emas,emas palsu,polres bengkalis,polda riau,melindungi tuah marwah,detik
3,Minyakita Tak Sesuai Ukuran juga Ditemukan di ...,"Senin, 10 Mar 2025 23:15 WIB",https://news.detik.com/berita/d-7816829/minyak...,Polisi mendatangi salah satu gudang Minyakita ...,minyakita,kudus,NaN,NaN,NaN,detik
4,"Pimpin LDP, Sanae Takaichi Calon Kuat PM Perem...",4 Oktober 2025 | 14.00 WIB,https://www.tempo.co/internasional/pimpin-ldp-...,"Baca berita dengan sedikit iklan, klik di sin...",jepang,perdana-menteri,sanae-takaichi,perempuan,ldp,tempo

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80472 entries, 0 to 80471
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Judul    80472 non-null  object
 1   Waktu    80472 non-null  object
 2   Link     80472 non-null  object
 3   Content  80463 non-null  object
 4   tag1     78023 non-null  object
 5   tag2     77612 non-null  object
 6   tag3     71602 non-null  object
 7   tag4     56856 non-null  object
 8   tag5     35633 non-null  object
 9   source   80472 non-null  object
dtypes: object(10)
memory usage: 6.1+ MB

In [4]:
df.shape

(80472, 10)

In [5]:
# Cek tag 20 teratas pada tag1
print(df['tag1'].value_counts().head(20))

tag1
Jakarta             865
prabowo subianto    774
kpk                 743
prabowo             635
Prabowo             541
KPK                 501
Pramono Anung       415
Ridwan Kamil        340
kebakaran           339
jokowi              327
israel              311
info-tempo          305
mpr                 260
banjir              258
gempa               253
pramono anung       244
kecelakaan          239
PDI-P               235
Prabowo Subianto    222
mbg                 221
Name: count, dtype: int64

In [6]:
# Cek tag 20 teratas pada tag2
print(df['tag2'].value_counts().head(20))

tag2
jabodetabek         488
prabowo subianto    471
info-tempo          423
prabowo             417
Pilkada Jakarta     352
israel              290
korupsi             290
kpk                 258
KPK                 240
Prabowo             232
Pramono Anung       217
Jokowi              216
pilkada 2024        216
bogor               198
jokowi              195
bmkg                191
imsakiyah           180
pilkada             175
Prabowo Subianto    175
dpr                 167
Name: count, dtype: int64

#### Mapping

In [7]:
def map_label(row):
    # Gabungkan tag1 dan tag2 untuk pengecekan lebih akurat
    tags = f"{str(row['tag1']).lower()} {str(row['tag2']).lower()}"
    
    if any(x in tags for x in ['prabowo', 'jokowi', 'pramono', 'ridwan kamil', 'mpr', 'dpr', 'pdi-p', 'pilkada', 'ldp']):
        return 'Politik'
    elif any(x in tags for x in ['kpk', 'korupsi', 'polisi', 'polres', 'polda', 'hukum', 'sidang']):
        return 'Hukum_Kriminal'
    elif any(x in tags for x in ['kebakaran', 'banjir', 'gempa', 'bmkg', 'kecelakaan', 'bencana']):
        return 'Bencana'
    elif any(x in tags for x in ['israel', 'internasional', 'luar negeri', 'pm']):
        return 'Internasional'
    elif any(x in tags for x in ['jakarta', 'jabodetabek', 'bogor', 'nasional']):
        return 'Nasional'
    else:
        return 'Lainnya'

df['category'] = df.apply(map_label, axis=1)

# Cek hasil distribusi kategori baru
print(df['category'].value_counts())

category
Lainnya           53719
Politik           12303
Hukum_Kriminal     5550
Nasional           4323
Bencana            3380
Internasional      1197
Name: count, dtype: int64

In [8]:
# Menghapus kategori Lainnya agar model fokus pada kategori yang jelas
df = df[df['category'] != 'Lainnya'].reset_index(drop=True)

# Cek distribusi baru
print(df['category'].value_counts())

category
Politik           12303
Hukum_Kriminal     5550
Nasional           4323
Bencana            3380
Internasional      1197
Name: count, dtype: int64

In [9]:
# Menyeimbangkan data agar model tidak bias
df_balanced = df.groupby('category').apply(lambda x: x.sample(n=min(len(x), 4000), random_state=42)).reset_index(drop=True)

print(df_balanced['category'].value_counts())

category
Hukum_Kriminal    4000
Politik           4000
Nasional          4000
Bencana           3380
Internasional     1197
Name: count, dtype: int64

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4424\1695827830.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_balanced = df.groupby('category').apply(lambda x: x.sample(n=min(len(x), 4000), random_state=42)).reset_index(drop=True)

#### PreProcesing

In [10]:
pip install swifter

Requirement already satisfied: swifter in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.4.0)
Requirement already satisfied: pandas>=1.0.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from swifter) (2.3.2)
Requirement already satisfied: psutil>=5.6.6 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from swifter) (7.1.0)
Requirement already satisfied: dask>=2.10.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask[dataframe]>=2.10.0->swifter) (2025.11.0)
Requirement already satisfied: tqdm>=4.33.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from swifter) (4.67.1)
Requirement already satisfied: click>=8.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (2025.12.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (25.0)
Requirement already satisfied: partd>=1.4.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.1.0)
Requirement already satisfied: colorama in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click>=8.1->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (0.4.6)
Requirement already satisfied: pyarrow>=14.0.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dask[dataframe]>=2.10.0->swifter) (22.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.0->swifter) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.0->swifter) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.0->swifter) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.0->swifter) (2025.2)
Requirement already satisfied: locket in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from partd>=1.4.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.0.0)
Requirement already satisfied: six>=1.5 in c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->swifter) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import swifter
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from tqdm import tqdm 

# 1. Inisialisasi Stopword dan Stemmer (Sastrawi)
sw_factory = StopWordRemoverFactory()
stop_words = set(sw_factory.get_stop_words())

st_factory = StemmerFactory()
stemmer = st_factory.create_stemmer()

# Langkah 1 CLeaning Basic
def basic_cleaning(text):
    text = str(text).lower()
    text = text.replace('baca berita dengan sedikit iklan, klik di sini', '')
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

print("Menjalankan Cleaning Dasar....")
df['temp_clean'] = df['Content'].swifter.apply(basic_cleaning)

# Langkah 2 Stemming
print("Membuat Dictionary Stemming....")
all_words = set("".join(df['temp_clean']).split())
unique_words = [w for w in all_words if w not in stop_words] 

word_map = {}
for word in tqdm(unique_words, desc="Stemming progpress"):
    word_map[word] = stemmer.stem(word)

# Langkah 3 Mapping
def procesing(text):
    tokens = text.split()
    stemmed_tokens = [word_map[w] for w in tokens if w in word_map]
    return stemmed_tokens

print("Menyusun Hasil Akhir.....")
df['cleaned_text'] = df['temp_clean'].swifter.apply(procesing)

# Hapus kolom
df.drop(columns=['temp_clean'], inplace=True)

# Simpan hasil
df.to_csv('dataset_processing.csv', index=False)
print("Selesai dan Tersimpan")

Menjalankan Cleaning Dasar....

Pandas Apply:   0%|          | 0/26753 [00:00<?, ?it/s]

Membuat Dictionary Stemming....

Stemming progpress: 100%|██████████| 78408/78408 [3:15:51<00:00,  6.67it/s]

Menyusun Hasil Akhir.....

Pandas Apply:   0%|          | 0/26753 [00:00<?, ?it/s]

Selesai dan Tersimpan

#### Load Dataset Hasil Procesing

In [14]:
df_procesing = pd.read_csv('../data/dataset_processing.csv')
df_procesing['cleaned_text'].head()

0    ['gempa', 'bumi', 'kuat', 'magnitudo', 'm', 'g...
1    ['presiden', 'prabowo', 'subianto', 'temu', 'g...
2    ['jakarta', 'kompas', 'com', 'wakil', 'ketua',...
3    ['tangerang', 'selatan', 'kompas', 'com', 'ora...
4    ['jakarta', 'kompas', 'com', 'bakar', 'landa',...
Name: cleaned_text, dtype: object

In [16]:
from IPython.display import display, HTML

# Tampilkan tabel dengan lebar kolom tertentu
display(HTML(df[['cleaned_text']].head(10).to_html().replace('<td>', '<td style="max-width: 2500px; word-wrap: break-word;">')))